
spring:
  datasource:
    url: mysql://root:pIhzXGbRkMTpKUSIQBtTkygAmLVKmSHa@mysql.railway.internal:3306/railway
    username: root
    password: pIhzXGbRkMTpKUSIQBtTkygAmLVKmSHa
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
